Controllers/AnnouncementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebA.Models;


namespace WebA.Controllers
{
    public class AnnouncementsController : Controller
    {
        private readonly NestStudentContext _context;

        public AnnouncementsController(NestStudentContext context)
        {
            _context = context;
        }

        // GET: Announcements
        public async Task<IActionResult> Index()
        {
            return _context.Announcements != null ?
                        View(await _context.Announcements.ToListAsync()) :
                        Problem("Entity set 'demoContext.Announcement'  is null.");
        }
        public async Task<IActionResult> HousemasterAnnouncement()
        {
            return _context.Announcements != null ?
                        View(await _context.Announcements.ToListAsync()) :
                        Problem("Entity set 'demoContext.Announcement'  is null.");
        }
        public async Task<IActionResult> StudentAnnouncement()
        {
            return _context.Announcements != null ?
                        View(await _context.Announcements.ToListAsync()) :
                        Problem("Entity set 'demoContext.Announcement'  is null.");
        }

        // GET: Announcements/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Announcements == null)
            {
                return NotFound();
            }

            var announcement = await _context.Announcements
                .FirstOrDefaultAsync(m => m.Id == id);
            if (announcement == null)
            {
                return NotFound();
            }

            return View(announcement);
        }

        // GET: Announcements/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Announcements/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,ReleaseDate")] Announcement announcement)
        {
            if (ModelState.IsValid)
            {
                _context.Add(announcement);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(HousemasterAnnouncement));
            }
            return View(announcement);
        }

        // GET: Announcements/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Announcements == null)
            {
                return NotFound();
            }

            var announcement = await _context.Announcements.FindAsync(id);
            if (announcement == null)
            {
                return NotFound();
            }
            return View(announcement);
        }

        // POST: Announcements/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,ReleaseDate")] Announcement announcement)
        {
            if (id != announcement.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(announcement);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnnouncementExists(announcement.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(HousemasterAnnouncement));
            }
            return View(announcement);
        }

        // GET: Announcements/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Announcements == null)
            {
                return NotFound();
            }

            var announcement = await _context.Announcements
                .FirstOrDefaultAsync(m => m.Id == id);
            if (announcement == null)
            {
                return NotFound();
            }

            return View(announcement);
        }

        // POST: Announcements/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Announcements == null)
            {
                return Problem("Entity set 'demoContext.Announcement'  is null.");
            }
            var announcement = await _context.Announcements.FindAsync(id);
            if (announcement != null)
            {
                _context.Announcements.Remove(announcement);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(HousemasterAnnouncement));
        }

        private bool AnnouncementExists(int id)
        {
          return (_context.Announcements?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/AskForLeaveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebA.Models;

namespace WebA.Controllers
{
    public class AskForLeaveController : Controller
    {
        private readonly NestStudentContext _context;

        public AskForLeaveController(NestStudentContext context)
        {
            _context = context;
        }

        // GET: AskForLeave
       
        public async Task<IActionResult> askforleave_housemaster()
        {
            return View(await _context.AskForLeaves.ToListAsync());
        }
        public async Task<IActionResult> askforleave_student()
        {
            return View(await _context.AskForLeaves.ToListAsync());
        }

        // GET: AskForLeave/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var askForLeave = await _context.AskForLeaves
                .FirstOrDefaultAsync(m => m.StudentId == id);
            if (askForLeave == null)
            {
                return NotFound();
            }

            return View(askForLeave);
        }

        // GET: AskForLeave/Create
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,StudentId,Reason,Date,SelectedOption")] AskForLeave askForLeave)
        {
            if (ModelState.IsValid)
            {
                _context.Add(askForLeave);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(askforleave_student));
            }
            return View(askForLeave);
        }

        // GET: AskForLeave/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var askForLeave = await _context.AskForLeaves.FirstOrDefaultAsync(m => m.AskForLeaveId == id);
            if (askForLeave == null)
            {
                return NotFound();
            }
            return View(askForLeave);
        }

        // POST: AskForLeave/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,AskForLeaveId,StudentId,Reason,Date,SelectedOption")] AskForLeave askForLeave)
        {
            if (id != askForLeave.AskForLeaveId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(askForLeave);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AskForLeaveExists(askForLeave.AskForLeaveId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(askforleave_housemaster));
            }
            return View(askForLeave);
        }

        // GET: AskForLeave/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var askForLeave = await _context.AskForLeaves
                .FirstOrDefaultAsync(m => m.StudentId == id);
            if (askForLeave == null)
            {
                return NotFound();
            }

            return View(askForLeave);
        }

        // POST: AskForLeave/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var askForLeave = await _context.AskForLeaves.FindAsync(id);
            if (askForLeave != null)
            {
                _context.AskForLeaves.Remove(askForLeave);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(askforleave_student));
        }

       
       
        private bool AskForLeaveExists(int id)
        {
            return _context.AskForLeaves.Any(e => e.StudentId == id);
        }
    }
}

Controllers/MainController.cs
using WebA.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace demo.Controllers
{
    public class MainController : Controller
    {
        private readonly ILogger<MainController> _logger;

        public MainController(ILogger<MainController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Housemaster_page()
        {
            return View();
        }
        public IActionResult Studentform_page()
        {
            return View();
        }
        public IActionResult Student_related_information()
        {
            return View();
        }
        public IActionResult Student_service_status()
        {
            return View();
        }
        public IActionResult Student_page()
        {
            return View();
        }
      
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NEST_5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NEST_5.styles.css" asp-append-version="true" />
    <style>
        .button-container {
            display: flex;
            flex-direction: column;
            gap: 10px; /* 添加按钮之间的间距 */
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Main" asp-action="Index">NEST_5</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Main" asp-action="Housemaster_page">舍監端</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Main" asp-action="Student_page">住宿生端</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RollCallStudents" asp-action="Index">(舍監)點名狀態</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RollCallStudents" asp-action="Create">(學生)點名</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AskForLeave" asp-action="Index2">(舍監)請假名單</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AskForLeave" asp-action="Index">(學生)請假填寫</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Announcements" asp-action="HousemasterAnnouncement">公告(舍監)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Announcements" asp-action="StudentAnnouncement">公告(住宿生)</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
       
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>