Models/Pay.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebA.Models;

public partial class Pay
{
    public int Id { get; set; }

    public byte[]? ImageData { get; set; }

    public string? ImageMimeType { get; set; }

    [NotMapped]
    public IFormFile? ImageFile { get; set; }
}

Controllers/ServersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebA.Models;

namespace demo.Controllers
{
    public class ServersController : Controller
    {
        private readonly NestStudentContext _context;

        public ServersController(NestStudentContext context)
        {
            _context = context;
        }

        // GET: Servers
       
        public async Task<IActionResult> servers_housemaster()
        {
            return _context.Servers != null ?
                        View(await _context.Servers.ToListAsync()) :
                        Problem("Entity set 'demoContext.Server'  is null.");
        }
        public async Task<IActionResult> servers_student()
        {
            return _context.Servers != null ?
                        View(await _context.Servers.ToListAsync()) :
                        Problem("Entity set 'demoContext.Server'  is null.");
        }


        // GET: Servers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Servers == null)
            {
                return NotFound();
            }

            var server = await _context.Servers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (server == null)
            {
                return NotFound();
            }

            return View(server);
        }

        // GET: Servers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Servers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,StudentId,Name,Major,Grade,Class,Gender,PhoneNumber,IDNumber,InitialPassword,Date,SelectedOption")] Server server)
        {
            if (ModelState.IsValid)
            {
                _context.Add(server);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(servers_student));
            }
            return View(server);
        }

        // GET: Servers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Servers == null)
            {
                return NotFound();
            }

            var server = await _context.Servers.FindAsync(id);
            if (server == null)
            {
                return NotFound();
            }
            return View(server);
        }

        // POST: Servers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,StudentId,Name,Major,Grade,Class,Gender,PhoneNumber,IDNumber,InitialPassword,Date,SelectedOption")] Server server)
        {
            if (id != server.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(server);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServerExists(server.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(servers_housemaster));
            }
            return View(server);
        }

        // GET: Servers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Servers == null)
            {
                return NotFound();
            }

            var server = await _context.Servers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (server == null)
            {
                return NotFound();
            }

            return View(server);
        }

        // POST: Servers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Servers == null)
            {
                return Problem("Entity set 'demoContext.Server'  is null.");
            }
            var server = await _context.Servers.FindAsync(id);
            if (server != null)
            {
                _context.Servers.Remove(server);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(servers_housemaster));
        }
        
        private bool ServerExists(int id)
        {
          return (_context.Servers?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/paysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebA.Models;

namespace demo.Controllers
{
    public class paysController : Controller
    {
        private readonly NestStudentContext _context;

        public paysController(NestStudentContext context)
        {
            _context = context;
        }

        // GET: pays
        public async Task<IActionResult> pays_student()
        {
            return _context.Pays != null ?
                        View(await _context.Pays.ToListAsync()) :
                        Problem("Entity set 'demoContext.pay'  is null.");
        }

        // GET: pays/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Pays == null)
            {
                return NotFound();
            }

            var pay = await _context.Pays
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pay == null)
            {
                return NotFound();
            }

            return View(pay);
        }

        // GET: pays/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: pays/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ImageData,ImageMimeType,ImageFile")] Pay pay)
        {
            if (ModelState.IsValid)
            {
                if (pay.ImageFile != null && pay.ImageFile.Length > 0)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        await pay.ImageFile.CopyToAsync(memoryStream);
                        pay.ImageData = memoryStream.ToArray();
                        pay.ImageMimeType = pay.ImageFile.ContentType;
                    }
                }

                _context.Add(pay);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(pays_housemaster));
            }
            else
            {
                // 打印 ModelState 错误信息
                var errors = ModelState.SelectMany(x => x.Value.Errors)
                                       .Select(e => e.ErrorMessage)
                                       .ToList();
                ViewBag.Errors = errors;
            }
            return View(pay);
        }
        

        // GET: pays/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Pays == null)
            {
                return NotFound();
            }

            var pay = await _context.Pays.FindAsync(id);
            if (pay == null)
            {
                return NotFound();
            }
            return View(pay);
        }

        // POST: pays/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ImageData,ImageMimeType")] Pay pay)
        {
            if (id != pay.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pay);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!payExists(pay.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(pays_student));
            }
            return View(pay);
        }

        // GET: pays/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Pays == null)
            {
                return NotFound();
            }

            var pay = await _context.Pays
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pay == null)
            {
                return NotFound();
            }

            return View(pay);
        }

        // POST: pays/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Pays == null)
            {
                return Problem("Entity set 'demoContext.pay'  is null.");
            }
            var pay = await _context.Pays.FindAsync(id);
            if (pay != null)
            {
                _context.Pays.Remove(pay);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(pays_housemaster));
        }
        public async Task<IActionResult> pays_housemaster()
        {
            return _context.Pays != null ?
                        View(await _context.Pays.ToListAsync()) :
                        Problem("Entity set 'demoContext.pay'  is null.");
        }
        public async Task<IActionResult> pays_housemaster_photo()
        {
            return _context.Pays != null ?
                        View(await _context.Pays.ToListAsync()) :
                        Problem("Entity set 'demoContext.pay'  is null.");
        }
       
        private bool payExists(int id)
        {
          return (_context.Pays?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/pays/Create.cshtml
@model WebA.Models.Pay

@{
    ViewData["Title"] = "Create";
}

<style>
    body {
        background-color: #fff7df; /* 替换为你需要的背景颜色 */
    }

    .custom-btn {
        background-color: #FFA629;
        border-color:#FFA629;
        color: black;
        margin-top:30px;
        font-weight: bold; /* 設置文字粗體 */
        /* 添加其他样式 */
    }

</style>
<div style="margin-bottom: 10px;">
    <img src="/img/toprenewpay.jpg" alt="更新繳費上" style="display: block; width: 100%; height: auto;">
</div>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group" style=" margin-top:30px;">
               
                <input asp-for="ImageFile" class="form-control" type="file" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary custom-btn " />
            </div>
        </form>
    </div>
</div>


@if (ViewBag.Errors != null)
{
    <div class="alert alert-danger">
        <ul>
            @foreach (var error in ViewBag.Errors)
            {
                <li>@error</li>
            }
        </ul>
    </div>
}
<div style="margin-bottom: 20px;">
    <img src="/img/icon.jpg" alt="icon" style="display: block; position: fixed;
            bottom: 10px;right: 10px;margin-left:10px; width: 35%; height: auto;">
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/pays/Delete.cshtml
@model WebA.Models.Pay

@{
    ViewData["Title"] = "Delete";
}
<style>
    body {
        background-color: #fff7df; /* 替换为你需要的背景颜色 */
    }

    .custom-btn {
        background-color: #FFA629;
        border-color: #FFA629;
        color: black;
        margin-top: 50px;
        font-weight: bold; /* 設置文字粗體 */
        /* 添加其他样式 */
    }

    .btn-primary {
        position: absolute;
        background-color: #FFA629;
        border-color: #FFA629;
        color: black;
        top: 141.5px;
        left: 47px;
        font-weight: bold; /* 設置文字粗體 */
        /* 添加其他样式 */
    }

    .custom-h4 {
        font-weight:bold;
     
    }

  

</style>
<h5 class="custom-h4">
    確定刪除?
</h5>


<div>
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="是" class="btn btn-danger custom-btn" /> 
        
    </form>
</div>
<button onclick="location.href='@Url.Action("pays_horsemaster", "pays")'" class="btn btn-primary">否</button>

Views/pays/Details.cshtml
@model WebA.Models.Pay

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>pay</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageData)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageData)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageMimeType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageMimeType)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/pays/Edit.cshtml
@model WebA.Models.Pay

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>pay</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ImageData" class="control-label"></label>
                <input asp-for="ImageData" class="form-control" />
                <span asp-validation-for="ImageData" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageMimeType" class="control-label"></label>
                <input asp-for="ImageMimeType" class="form-control" />
                <span asp-validation-for="ImageMimeType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/pays/pays_housemaster.cshtml
@model IEnumerable<WebA.Models.Pay>

@{
    ViewData["Title"] = "本期繳費";
}
<style>
    body {
        background-color: #fff7df; /* 替换为你需要的背景颜色 */
    }

    .center {
        display: flex;
        justify-content: center; /* 將內容水平置中 */
        
    }

    .update-link {
        display: inline-block;
        margin-top: 5px;
        padding: 5px 10px; /* Smaller padding */
        background-color: #FFA629; /* Background color for the link */
        color: black; /* Text color */
        text-decoration: none;
        border-radius: 3px; /* Smaller rounded corners */
        border: 1px solid #FFA629; /* Border */
        font-size: 16px; /* Adjust the font size as needed */
        font-weight: bold; /* Make the font bold */
    }

        .update-link:hover {
            background-color: #FFA629; /* Darker shade on hover */
        }

    .delete-link {
        display: inline-block;
        padding: 5px 10px;
        background-color: #FFA629; /* 设置背景色为红色，你可以根据需要修改 */
        color: black; /* 文本颜色 */
        text-decoration: none;
        border: 1px solid #FFA629; /* 设置边框 */
        border-radius: 3px; /* 圆角 */
        margin-top:120px;
        font-size: 14px; /* Adjust the font size as needed */
        font-weight: bold; /* Make the font bold */
    }

        .delete-link:hover {
            background-color: #FFA629; /* 鼠标悬停时的背景色 */
            border: 1px solid #FFA629; /* 鼠标悬停时的边框颜色 */
        }

    .table {
        width: 100%;
        border-collapse: collapse;
        background-color: #FFE183; /* 表格背景颜色 */
    }
</style>
<div style="margin-bottom: 20px;">
<img src="/img/toprenewpay.jpg" alt="更新繳費上" style="display: block; width: 100%; height: auto;">
</div>
<div class="table-wrapper">
    <table class="table">
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @if (item.ImageData != null && item.ImageData.Length > 0)
                        {
                            <img src="data:@item.ImageMimeType;base64,@Convert.ToBase64String(item.ImageData)" width="270" height="270" />
                        }
                        else
                        {
                            <span>No image available</span>
                        }
                    </td>
                    <td>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="delete-link">刪除</a>
                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>

<div class="center">
    <a asp-action="Create" class="update-link">更新水電費收款碼</a>
  
</div>

Views/pays/pays_housemaster_photo.cshtml
@model IEnumerable<WebA.Models.Pay>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Image Hover Animation</title>
    <style>
        body {
            background-color: #fff7df; /* 替换为你需要的背景颜色 */
            font-family: Arial, sans-serif;
        }

        .image-container {
            position: relative;
            display: inline-block;
            margin-right: 15px;
            transition: transform 0.3s ease, box-shadow 0.3s ease;
        }

            .image-container img {
                width: 95%;
                height: auto;
                padding: 5px;
                margin-left: 15px;
                transition: transform 0.3s ease, box-shadow 0.3s ease;
            }

            .image-container:hover img {
                transform: scale(1.05);
                box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);
            }

        .top-image-container {
            margin-bottom: 20px;
        }

        .bottom-images {
            display: flex;
            flex-wrap: wrap;
        }
    </style>
</head>
<body>
    <div class="top-image-container">
        <img src="/img/toppay.jpg" alt="繳費上" style="display: block; width: 100%; height: auto;">
    </div>
    <div class="bottom-images">
        <div class="image-container">
            <img src="/img/renewpay.png" alt="更新繳費狀態" onclick="location.href='@Url.Action("servers_housemaster", "Servers")';">
        </div>
        <div class="image-container" style="margin-top: 20px;">
            <img src="/img/utilitybills qrcode.png" alt="水電費收款碼" onclick="location.href='@Url.Action("pays_horsemaster", "pays")';">
        </div>
    </div>
</body>
</html>

Views/pays/pays_student.cshtml
@model IEnumerable<WebA.Models.Pay>

@{
    ViewData["Title"] = "本期繳費";
}

<style>
    body {
        background-color: #fff7df; /* 替换为你需要的背景颜色 */
    }

    .center {
        display: flex;
        justify-content: center; /* 將內容水平置中 */
    }

    .table {
        width: auto; /* 设置为 auto 以适应内容宽度 */
        border-collapse: collapse;
        background-color: #FFE183; /* 表格背景颜色 */
        margin: 0 auto; /* 水平居中 */
    }

    .custom-h5 {
        border: 2px solid #FFA629; /* 设置边框颜色和粗细 */
        background-color: #FFA629; /* 设置背景颜色 */
        color: black; /* 设置文字颜色 */
        padding: 10px; /* 添加内边距 */
        text-align: center; /* 使文本居中 */
        border-radius: 5px; /* 添加圆角 */
        display: inline-block; /* 使元素的宽度适应内容 */
        margin: 20px auto; /* 添加上下外边距，并水平居中 */
        font-weight: bold;
    }

    .download-link {
        color: #FFA629;
        text-decoration: none;
        font-weight: bold;
    }

        .download-link:hover {
            text-decoration: underline;
        }

    .container {
        text-align: center;
    }
</style>
<div style="margin-bottom: 10px;">
    <img src="/img/toppay.jpg" alt="繳費上" style="display: block; width: 100%; height: auto;">
</div>
<div class="table-wrapper center">
    <table class="table">
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @if (item.ImageData != null && item.ImageData.Length > 0)
                        {
                            <a href="data:@item.ImageMimeType;base64,@Convert.ToBase64String(item.ImageData)" download="image.jpg">
                                <img src="data:@item.ImageMimeType;base64,@Convert.ToBase64String(item.ImageData)" width="300" height="300" />
                            </a>
                            <div style="text-align: center; margin-top: 5px;">
                                <a href="data:@item.ImageMimeType;base64,@Convert.ToBase64String(item.ImageData)" download="image.jpg" class="download-link">下載圖片</a>
                            </div>

                        }
                        else
                        {
                            <span>No image available</span>
                        }

                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="container">
    <h5 class="custom-h5">
        記得繳費喔!!
    </h5>
</div>