Controllers/MainController.cs
using WebA.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace demo.Controllers
{
    public class MainController : Controller
    {
        private readonly ILogger<MainController> _logger;

        public MainController(ILogger<MainController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Housemaster_page()
        {
            return View();
        }
        public IActionResult Studentform_page()
        {
            return View();
        }
        public IActionResult Student_related_information()
        {
            return View();
        }
        public IActionResult Student_service_status()
        {
            return View();
        }
        public IActionResult Student_page()
        {
            return View();
        }
      
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/fixesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebA.Models;

namespace WebA.Controllers
{
    public class fixesController : Controller
    {
        private readonly NestStudentContext _context;

        public fixesController(NestStudentContext context)
        {
            _context = context;
        }

        // GET: fixes
        public async Task<IActionResult> fix_student()
        {
              return _context.Fixes != null ? 
                          View(await _context.Fixes.ToListAsync()) :
                          Problem("Entity set 'demoContext.fix'  is null.");
        }

        // GET: fixes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Fixes == null)
            {
                return NotFound();
            }

            var fix = await _context.Fixes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (fix == null)
            {
                return NotFound();
            }

            return View(fix);
        }

        // GET: fixes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: fixes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Date,Project,Site")] Fix fix)
        {
            if (ModelState.IsValid)
            {
                _context.Add(fix);
                await _context.SaveChangesAsync();
                return RedirectToAction("Student_page", "Main");
            }
            return View(fix);
        }

        // GET: fixes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Fixes == null)
            {
                return NotFound();
            }

            var fix = await _context.Fixes.FindAsync(id);
            if (fix == null)
            {
                return NotFound();
            }
            return View(fix);
        }

        // POST: fixes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Date,Project,Site,SelectedOption")] Fix fix)
        {
            if (id != fix.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(fix);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!fixExists(fix.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(fix_housemaster));
            }
            return View(fix);
        }

        // GET: fixes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Fixes == null)
            {
                return NotFound();
            }

            var fix = await _context.Fixes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (fix == null)
            {
                return NotFound();
            }

            return View(fix);
        }

        // POST: fixes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Fixes == null)
            {
                return Problem("Entity set 'demoContext.fix'  is null.");
            }
            var fix = await _context.Fixes.FindAsync(id);
            if (fix != null)
            {
                _context.Fixes.Remove(fix);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(fix_housemaster));
        }
        public async Task<IActionResult> fix_housemaster()
        {
            return _context.Fixes != null ?
                        View(await _context.Fixes.ToListAsync()) :
                        Problem("Entity set 'demoContext.fix'  is null.");
        }
        
        [HttpPost]
     

        private bool fixExists(int id)
        {
          return (_context.Fixes?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/paysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebA.Models;

namespace demo.Controllers
{
    public class paysController : Controller
    {
        private readonly NestStudentContext _context;

        public paysController(NestStudentContext context)
        {
            _context = context;
        }

        // GET: pays
        public async Task<IActionResult> pays_student()
        {
            return _context.Pays != null ?
                        View(await _context.Pays.ToListAsync()) :
                        Problem("Entity set 'demoContext.pay'  is null.");
        }

        // GET: pays/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Pays == null)
            {
                return NotFound();
            }

            var pay = await _context.Pays
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pay == null)
            {
                return NotFound();
            }

            return View(pay);
        }

        // GET: pays/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: pays/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ImageData,ImageMimeType,ImageFile")] Pay pay)
        {
            if (ModelState.IsValid)
            {
                if (pay.ImageFile != null && pay.ImageFile.Length > 0)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        await pay.ImageFile.CopyToAsync(memoryStream);
                        pay.ImageData = memoryStream.ToArray();
                        pay.ImageMimeType = pay.ImageFile.ContentType;
                    }
                }

                _context.Add(pay);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(pays_housemaster));
            }
            else
            {
                // 打印 ModelState 错误信息
                var errors = ModelState.SelectMany(x => x.Value.Errors)
                                       .Select(e => e.ErrorMessage)
                                       .ToList();
                ViewBag.Errors = errors;
            }
            return View(pay);
        }
        

        // GET: pays/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Pays == null)
            {
                return NotFound();
            }

            var pay = await _context.Pays.FindAsync(id);
            if (pay == null)
            {
                return NotFound();
            }
            return View(pay);
        }

        // POST: pays/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ImageData,ImageMimeType")] Pay pay)
        {
            if (id != pay.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pay);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!payExists(pay.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(pays_student));
            }
            return View(pay);
        }

        // GET: pays/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Pays == null)
            {
                return NotFound();
            }

            var pay = await _context.Pays
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pay == null)
            {
                return NotFound();
            }

            return View(pay);
        }

        // POST: pays/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Pays == null)
            {
                return Problem("Entity set 'demoContext.pay'  is null.");
            }
            var pay = await _context.Pays.FindAsync(id);
            if (pay != null)
            {
                _context.Pays.Remove(pay);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(pays_housemaster));
        }
        public async Task<IActionResult> pays_housemaster()
        {
            return _context.Pays != null ?
                        View(await _context.Pays.ToListAsync()) :
                        Problem("Entity set 'demoContext.pay'  is null.");
        }
        public async Task<IActionResult> pays_housemaster_photo()
        {
            return _context.Pays != null ?
                        View(await _context.Pays.ToListAsync()) :
                        Problem("Entity set 'demoContext.pay'  is null.");
        }
       
        private bool payExists(int id)
        {
          return (_context.Pays?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/suesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebA.Models;

namespace demo.Controllers
{
    public class suesController : Controller
    {
        private readonly NestStudentContext _context;

        public suesController(NestStudentContext context)
        {
            _context = context;
        }

        // GET: sues
       
        public async Task<IActionResult> sues_housemaster()
        {
            return _context.Sues != null ?
                        View(await _context.Sues.ToListAsync()) :
                        Problem("Entity set 'demoContext.sue'  is null.");
        }
        public async Task<IActionResult> sues_student()
        {
            return _context.Sues != null ?
                        View(await _context.Sues.ToListAsync()) :
                        Problem("Entity set 'demoContext.sue'  is null.");
        }
        // GET: sues/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Sues == null)
            {
                return NotFound();
            }

            var sue = await _context.Sues
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sue == null)
            {
                return NotFound();
            }

            return View(sue);
        }

        // GET: sues/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: sues/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Date,Reason,Roomnumber")] Sue sue)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sue);
                await _context.SaveChangesAsync();
                return RedirectToAction("Student_page", "Main");
            }
            return View(sue);
        }

        // GET: sues/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Sues == null)
            {
                return NotFound();
            }

            var sue = await _context.Sues.FindAsync(id);
            if (sue == null)
            {
                return NotFound();
            }
            return View(sue);
        }

        // POST: sues/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Date,Reason,Roomnumber,SelectedOption")] Sue sue)
        {
            if (id != sue.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sue);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!sueExists(sue.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(sues_housemaster));
            }
            return View(sue);
        }

        // GET: sues/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Sues == null)
            {
                return NotFound();
            }

            var sue = await _context.Sues
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sue == null)
            {
                return NotFound();
            }

            return View(sue);
        }

        // POST: sues/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Sues == null)
            {
                return Problem("Entity set 'demoContext.sue'  is null.");
            }
            var sue = await _context.Sues.FindAsync(id);
            if (sue != null)
            {
                _context.Sues.Remove(sue);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(sues_student));
        }
       

        private bool sueExists(int id)
        {
          return (_context.Sues?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Main/Housemaster_page.cshtml
<!DOCTYPE html>
<html lang="zh-Hant">
<head>
    <meta charset="UTF-8">
    <style>
        body {
            background-color: #fff7df; /* 替換為你需要的背景顏色 */
        }

        .container {
            position: relative;
            display: inline-block;
            width: 100%;
        }

        .bell-icon {
            position: absolute;
            top: 0px;
            left: 5px;
            width: 35px;
            height: 35px;
            cursor: pointer;
            z-index: 1; /* 保證鈴鐺在topnest圖片的上一層 */
            transition: transform 0.4s; /* 設置過渡效果 */
        }

        .bell-icon.flipped {
                transform: rotateY(180deg); /* 設置翻轉效果 */
         }

        .image-container img {
            transition: transform 0.3s ease, box-shadow 0.3s ease;
            margin-bottom: 15px; /* 將margin-bottom應用到img上 */
        }

        .image-container:hover img {
            transform: scale(1.05);
            box-shadow: 0 0px 0px rgba(0, 0, 0, 0.5);
        }
    </style>
</head>
<body>
    <div class="container">
        <img src="/img/bell.png" alt="鈴鐺" class="bell-icon" onclick="flipBell();">
        <img src="/img/topnest.jpg" alt="上" style="display: block; width: 100%; height: auto;">
    </div>

    <div style="margin-bottom: 20px; margin-top: 20px;">
        <div class="image-container" style="float: left; margin-left: 20px; width: 40%; box-sizing: border-box;">
            <img src="/img/studentinformation.png" alt="學生資料" style="width: 100%; height: auto;">
        </div>
        <div class="image-container" style="float: left; margin-left: 20px; width: 40%; box-sizing: border-box;">
            <img src="/img/roll call.png" alt="點名" style="width: 100%; height: auto;">
        </div>
        <div class="image-container" style="clear: both;"></div>
    </div>
    <div class="image-container" style="margin-bottom: 10px;">
        <img src="/img/sleep over.png" alt="外宿" style="display: block; width: 85%; height: auto; margin-left:25px;" onclick="location.href='@Url.Action("askforleave_housemaster", "AskForLeave")';">
    </div>
    <div class="image-container" style="margin-bottom: 10px;">
        <img src="/img/fixx.png" alt="報修" style="display:block; width: 85%; height: auto; margin-left:25px;" onclick="location.href='@Url.Action("fix_housemaster", "fixes")';">
    </div>
    <div class="image-container" style="margin-bottom: 10px;">
        <img src="/img/complaintt.png" alt="投訴" style="display: block; width: 85%; height: auto; margin-left:25px;" onclick="location.href='@Url.Action("sues_housemaster", "sues")';">
    </div>
    <div class="image-container" style="margin-bottom: 10px;">
        <img src="/img/utilitybills.png" alt="水電費" style="display: block; width: 85%; height: auto; margin-left:25px;" onclick="location.href='@Url.Action("pays_housemaster_photo", "pays")';">
    </div>

    <script>
        function flipBell() {
            var bell = document.querySelector('.bell-icon');
            bell.classList.add('flipped');
            setTimeout(function () {
                location.href = '@Url.Action("HousemasterAnnouncement", "Announcements")';
            }, 400); // 延遲與動畫持續時間匹配
        }
    </script>
</body>
</html>

Views/Main/Index.cshtml
<div class="text-center">
    <h1 class="display-4"></h1>
</div>

Views/Main/Student_page.cshtml
<style>
    body {
        background-color: #fff7df;
    }

    .container {
        position: relative;
        display: inline-block;
        width: 100%;
    }

    .image-container img {
        transition: transform 0.3s ease, box-shadow 0.3s ease;
        margin-bottom: 15px; /* 将margin-bottom应用到img上 */
    }

    .image-container:hover img {
        transform: scale(1.05);
        box-shadow: 0 1px 2px rgba(0, 0, 0, 0.5);
    }

    .bell-icon {
        position: absolute;
        top: 0px;
        left: 5px;
        width: 35px;
        height: 35px;
        cursor: pointer;
        z-index: 1; /* 保證鈴鐺在topnest圖片的上一層 */
        transition: transform 0.4s; /* 設置過渡效果 */
    }

        .bell-icon.flipped {
            transform: rotateY(180deg); /* 設置翻轉效果 */
        }
</style>

<div class="container">
    <img src="/img/bell.png" alt="鈴鐺" class="bell-icon" onclick="flipBell();">
    <img src="/img/topnest.jpg" alt="上" style="display: block; width: 100%; height: auto;margin-left: 5px;">
</div>
<div style="margin-left: 12px; margin-top: 30px;">
    <div class="image-container" style="position: relative; display: inline-block; margin-left: 18px;">
        <img src="/img/personal information.png" alt="個人資料">
    </div>
    <div class="image-container" style="position: relative; display: inline-block; margin-left: 18px;">
        <img src="/img/online roll call.png" alt="線上點名">
    </div>
    <div class="image-container" style="position: relative; display: inline-block; margin-left: 18px;">
        <img src="/img/write form.png" alt="填寫表單" style="width: 100%; height: auto;" onclick="location.href='@Url.Action("Studentform_page", "Main")';">
    </div>
    <div class="image-container" style="position: relative; display: inline-block; margin-left: 18px;">
        <img src="/img/service status.png" alt="服務狀態" onclick="location.href='@Url.Action("servers_student", "Servers")';">
    </div>
    <div class="image-container" style="position: relative; display: inline-block; margin-left: 18px;">
        <img src="/img/pay online.png" alt="線上繳費" style="width: 100%; height: auto;" onclick="location.href='@Url.Action("pays_student", "pays")';">
    </div>
    <div class="image-container" style="position: relative; display: inline-block; margin-left: 18px;">
        <img src="/img/relevant information.png" alt="相關資訊" onclick="location.href='@Url.Action("Student_related_information", "Main")';">
    </div>
</div>
<script>
    function flipBell() {
        var bell = document.querySelector('.bell-icon');
        bell.classList.add('flipped');
        setTimeout(function () {
            location.href = '@Url.Action("HousemasterAnnouncement", "Announcements")';
        }, 400); // 延遲與動畫持續時間匹配
    }
</script>

Views/Main/Student_related_information.cshtml
<style>
    body {
        background-color: #fff7df; /* 替换为你需要的背景颜色 */
    }
    
    .button-container {
        display: flex;
        flex-direction: column;
        align-items: center; /* 水平居中 */
        gap: 10px; /* 可調整按鈕之間的間距 */
    }

    .title {
        background-color: #BAB6AA; /* 標題底色 */
        padding: 5px; /* 標題內邊距 */
        border-radius: 25px; /* 圓角 */
        margin-bottom: 5px; /* 標題與按鈕間距 */
        height: 3rem; /* 高度 */
        width: 30%; /* 標題的寬度 */
        text-align: center; /* 文字水平居中 */
        font-size: 1.2rem; /* 調整字體大小 */
        line-height: 3rem; /* 文字垂直居中 */
        font-weight: bold;
        margin-right: auto; /* 将标题框向左移动到页面中间 */
        margin-left: 30px; /* 将标题框向左移动到页面中间 */
        display: flex; /* 使用 Flex 布局 */
        justify-content: center; /* 文字水平居中 */
        align-items: center; /* 垂直居中 */
        margin-bottom: 15px;
        
    }



    .btn {
        display: flex;
        justify-content: center;
        align-items: center;
        width: 60%; /* 與標題相同的寬度 */
        max-width: 25rem; /* 最大寬度 */
        height: 2.3rem; /* 按鈕高度 */
        font-weight: bold;
        letter-spacing: 0.05rem;
        text-transform: uppercase;
        font-size: 1.05rem;
        border-radius: 25px; /* 圓角 */
        background-color: transparent; /* 背景顏色 */
        border: 3px solid #BAB6AA; /* 邊框顏色 */
        box-shadow:  -2px -2px 2px #cecece; /* 內凹立體感 */
        cursor: pointer;
        color: black; /* 文字顏色 */
        text-decoration: none; /* 禁用超連結下劃線 */
        margin-bottom: 10px;
        text-align: center; /* 水平居中 */
        transition: background-color 0s ease;
    }

        .btn:hover {
            background-color: #FFCD29; /* 懸停時的背景顏色 */
            color: black;
            border-color: #FFCD29;
            
        }

   
</style>

<div style="margin-bottom: 10px;">
    <img src="/img/topschool.jpg" alt="學校上" style="display: block; width: 100%; height: auto;">
</div>
<div class="button-container">
    <div class="title">校園資源</div>
    <a href="https://web2.mcu.edu.tw" class="btn btn-primary">銘傳首頁</a>
    <a href="https://moodle3-06.mcu.edu.tw" class="btn btn-primary">Moodle</a>
    <a href="https://www.mcu.edu.tw/student/new-query/default.asp" class="btn btn-primary">學生資訊系統</a>
    <a href="https://web2.mcu.edu.tw/calendar/" class="btn btn-primary">行事曆</a>
    <a href="http://www1.mcu.edu.tw/Apps/SB/SB_Site.aspx?pageID=164&wcID=2371&redirected=true" class="btn btn-primary">校內分機</a>
    <a href="https://gad.mcu.edu.tw/transportation/" class="btn btn-primary">交通指南</a>
    <a href="https://www1.mcu.edu.tw/Apps/SB/SB_Page.aspx?pageid=2376&noframes=true" class="btn btn-primary">校園地圖</a>
    <a href="https://web2.mcu.edu.tw/news/" class="btn btn-primary">最新消息</a>
    <a href="https://library.mcu.edu.tw" class="btn btn-primary">圖書館</a>
    <a href="https://www.week.mcu.edu.tw/" class="btn btn-primary">銘傳一週</a>
    <div class="title">使用說明</div>
    <a href="" class="btn btn-primary">Nest平台相關操作說明</a>
    <a href="" class="btn btn-primary">聯絡我們</a>
    <a href="" class="btn btn-primary">隱私權說明</a>
    <div class="title">linebot</div>
    <img src="/img/linebot.png" alt="linebot" style="display: block; width: 50%; height: auto;">
   
   
</div>

Views/Main/Student_service_status.cshtml
<style>
    body {
        background-color: #fff7df; /* 替换为你需要的背景颜色 */
    }
<!--
    .button-container {
        position: relative;
        display: inline-block;
        width: 30%;
        height: auto;
       
        margin-right: 100px;
    }

     .button-container img {
            display: inline-block;
            width: 100%;
            height: auto;
        }
        -->
</style>
<div>
    <div>
        <img src="/img/topserver.png" alt="top" style="display: block; margin-bottom:30px; width: 100%; height: auto;">
    </div>
    <div style="display: flex; flex-wrap: wrap; gap: 10px;">
        <div style="flex: 1 1 45%; max-width: 45%;">
            <img src="/img/sleepoverserver.png" alt="填寫表單" style="width: 85%; margin-left:23px; height: auto; padding: 10px;" onclick="location.href='@Url.Action("servers_student", "Servers")';">
        </div>
        <div style="flex: 1 1 45%; max-width: 45%;">
            <img src="/img/fixserver.png" alt="填寫表單" style="width: 85%; margin-left:23px; height: auto; padding: 10px;" onclick="location.href='@Url.Action("servers_student", "Servers")';">
        </div>
        <div style="flex: 1 1 45%; max-width: 45%;">
            <img src="/img/complaintserver.png" alt="填寫表單" style="width: 85%; margin-left:23px; height: auto; padding: 10px;" onclick="location.href='@Url.Action("servers_student", "Servers")';">
        </div>
        <div style="flex: 1 1 45%; max-width: 45%;">
            <img src="/img/payserver.png" alt="填寫表單" style="width: 85%; margin-left:23px; height: auto; padding: 10px;" onclick="location.href='@Url.Action("servers_student", "Servers")';">
        </div>
    </div>
</div>




@*
<div class="button-container" onclick="location.href='@Url.Action("Index", "Servers")';">
    <img src="/img/sleepoverserver.png" alt="top">
</div>
<div class="button-container" onclick="location.href='@Url.Action("Index", "Servers")';">
    <img src="/img/fixserver.png" alt="top" >
</div>
<div class="button-container" onclick="location.href='@Url.Action("Index", "Servers")';">
    <img src="/img/complaintserver.png" alt="top" >
</div>

<div class="button-container" onclick="location.href='@Url.Action("Index", "Servers")';">
    <img src="/img/payserver.png" alt="投訴表單">
</div>
*@

Views/Main/Studentform_page.cshtml
<style>
    body {
        background-color: #fff7df; /* 替换为你需要的背景颜色 */
    }

    .button-container {
        display: block;
        width: 85%;
        height: auto;
        margin-bottom: 30px; /* 控制按钮间距 */
    }

        .button-container img {
            display: block;
            width: 100%;
            height: auto;
            margin-left: 25px;
            transition: transform 0.3s ease, box-shadow 0.3s ease; /* 添加动画过渡效果 */
        }

            .button-container img:active {
                transform: scale(1.05); /* 点击放大图片 */
                box-shadow: 0 0px 2px rgba(0, 0, 0, 0.5); /* 点击时添加阴影效果 */
            }
</style>

<div style="margin-bottom: 20px;">
    <img src="/img/top.jpg" alt="top" style="display: block; width: 100%; height: auto;">
</div>
<div class="button-container" onclick="location.href='@Url.Action("Create", "AskForLeave")';">
    <img src="/img/sleep form.png" alt="外宿表單">
</div>
<div class="button-container" onclick="location.href='@Url.Action("Create", "fixes")';">
    <img src="/img/fix form.png" alt="報修表單">
</div>
<div class="button-container" onclick="location.href='@Url.Action("Create", "sues")';">
    <img src="/img/complaintform.png" alt="投訴表單">
</div>